apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-app-secrets
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-app-secrets
    creationPolicy: Owner
  data:
    # Google OAuth
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: my-recipes/oauth/google-client-id
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: my-recipes/oauth/google-client-secret
    - secretKey: GOOGLE_REDIRECT_URI
      remoteRef:
        key: my-recipes/oauth/google-redirect-uri
    
    # Microsoft Entra ID (Azure AD) OAuth
    - secretKey: AZURE_CLIENT_ID
      remoteRef:
        key: my-recipes/oauth/azure-client-id
    - secretKey: AZURE_CLIENT_SECRET
      remoteRef:
        key: my-recipes/oauth/azure-client-secret
    - secretKey: AZURE_TENANT_ID
      remoteRef:
        key: my-recipes/oauth/azure-tenant-id
    - secretKey: AZURE_REDIRECT_URI
      remoteRef:
        key: my-recipes/oauth/azure-redirect-uri
    
    # Email Configuration
    - secretKey: SMTP_HOST
      remoteRef:
        key: my-recipes/email/smtp-host
    - secretKey: SMTP_PORT
      remoteRef:
        key: my-recipes/email/smtp-port
    - secretKey: SMTP_USER
      remoteRef:
        key: my-recipes/email/smtp-user
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: my-recipes/email/smtp-password
    - secretKey: SMTP_FROM
      remoteRef:
        key: my-recipes/email/smtp-from
    
    # S3 Configuration
    - secretKey: S3_ENDPOINT
      remoteRef:
        key: my-recipes/s3/endpoint
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: my-recipes/s3/access-key
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: my-recipes/s3/secret-key
    - secretKey: S3_BUCKET_NAME
      remoteRef:
        key: my-recipes/s3/bucket-name
    - secretKey: S3_REGION
      remoteRef:
        key: my-recipes/s3/region
    
    # Frontend URL - this can be templated since it's not sensitive
    - secretKey: FRONTEND_URL
      remoteRef:
        key: my-recipes/frontend/url
        property: url
